/**
 * The showcase's sound design as data (docs/audio/mission-sound-design.md):
 * every cue the mission plays, how it is generated (ElevenLabs prompt,
 * length, loop, variants) and how the engine plays it (bus, gain, variance,
 * cooldown, instance cap, spatial defaults).
 *
 * The engine's audio tools take this file as `--manifest`:
 * `tools/audio/generate.mjs` turns the prompts into raw takes under `PATHS.raw`,
 * `tools/audio/build.mjs` masters them into `PATHS.out` and writes
 * manifest.json there, which the game reads at scene load through the
 * engine's `SoundBank` (apps/showcase/src/audio/MissionAudio.ts). Names are
 * the contract between this file and the game; change one, change both.
 *
 * Prompt craft for ElevenLabs' text-to-sound model (its guide: short and
 * concrete, one sound per prompt, no cinematic words): name the source, the
 * texture and the mic distance; ask for "dry" one-shots so the engine's
 * spatialisation adds the room. `influence` is prompt_influence (0.3 default: more creative, 0.6+:
 * literal). Loops are requested with the API's loop flag and still get a
 * crossfaded seam in the build.
 */

/** @typedef {'sfx'|'ui'|'ambience'|'music'} Bus */

/**
 * @typedef {object} Cue
 * @property {string} name          engine sound name
 * @property {'sfx'|'voice'} kind   sound-effects endpoint, or text-to-speech (voice lines)
 * @property {string} prompt        what to generate (for voice: the words spoken)
 * @property {number} seconds       requested length, 0.5..22 (voice: ignored)
 * @property {number} [variants]    round-robin takes to generate (default 1)
 * @property {boolean} [loop]       seamless loop
 * @property {number} [influence]   prompt_influence 0..1
 * @property {Bus} bus
 * @property {number} volume        base gain
 * @property {number} [volumeVariance]
 * @property {number} [pitchVariance] semitones
 * @property {number} [cooldownMs]
 * @property {number} [maxInstances]
 * @property {boolean} [stereo]     keep stereo (beds); spatial one-shots are mono
 * @property {number} [lufs]        integrated loudness target for mastering (default by bus)
 * @property {string} [voiceStyle]  voice lines: 'ganger' (helmet comms filter) or 'operator'
 * @property {string} [note]        design intent, for the cue sheet
 */

/** Where the tools read and write, relative to the repo root. */
export const PATHS = { raw: 'assets/source/audio/raw', out: 'apps/showcase/public/audio' };

/** Loudness targets (LUFS integrated) so the mix balances before any in-game gain. */
export const LUFS = { sfx: -18, ui: -20, ambience: -26, voice: -19, music: -16 };

/** Enemy voice: a low, rough, tired male. Set VOICE_ID in .env to override the search. */
export const VOICE_SEARCH = { gender: 'male', keywords: ['deep', 'raspy', 'gruff', 'rough', 'low'] };

/** @type {Cue[]} */
export const CUES = [
  // ---- weapons ------------------------------------------------------------------
  {
    name: 'rifle-shot',
    kind: 'sfx',
    prompt: 'single suppressed assault rifle gunshot, close mic, tight punchy crack with a short mechanical action click, dry, no reverb tail',
    seconds: 1.0,
    variants: 4,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.9,
    volumeVariance: 0.08,
    pitchVariance: 1.2,
    cooldownMs: 30,
    maxInstances: 6,
    note: "the operator's rifle: near layer, played at the muzzle; the tail below is a second voice",
  },
  {
    name: 'rifle-tail',
    kind: 'sfx',
    prompt: 'gunshot echo tail only, reflecting off wet city street and tall concrete buildings at night, no initial crack, long decaying slapback',
    seconds: 2.2,
    variants: 3,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.5,
    volumeVariance: 0.1,
    pitchVariance: 0.8,
    cooldownMs: 60,
    maxInstances: 4,
    stereo: true,
    note: 'street slapback layered under every shot so the level answers the gun',
  },
  {
    name: 'rifle-distant',
    kind: 'sfx',
    prompt: 'distant assault rifle gunshot heard from two hundred meters away across a rainy city at night, muffled low thud with echo',
    seconds: 1.8,
    variants: 3,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.8,
    volumeVariance: 0.1,
    pitchVariance: 1.5,
    cooldownMs: 60,
    maxInstances: 6,
    note: 'enemy fire far away; crossfaded with rifle-shot by distance',
  },
  {
    name: 'rifle-reload',
    kind: 'sfx',
    prompt: 'assault rifle reload: magazine release click, empty magazine drops, fresh magazine slides in and seats with a solid click, bolt racked, close mic, dry',
    seconds: 2.5,
    variants: 2,
    influence: 0.6,
    bus: 'sfx',
    volume: 0.7,
    pitchVariance: 0.5,
    cooldownMs: 500,
    maxInstances: 2,
    note: "built to the rifle's 2.5 s reload time (combat/weapons.ts)",
  },
  {
    name: 'rifle-empty',
    kind: 'sfx',
    prompt: 'dry fire click of an empty assault rifle trigger, small metallic snap, close mic, dry',
    seconds: 0.5,
    variants: 2,
    influence: 0.6,
    bus: 'sfx',
    volume: 0.6,
    pitchVariance: 0.8,
    cooldownMs: 120,
    maxInstances: 1,
  },
  {
    name: 'aim-in',
    kind: 'sfx',
    prompt: 'soft quick tactical gear rustle and a faint rifle stock shoulder tap, very short, subtle foley, close mic, dry',
    seconds: 0.5,
    variants: 3,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.35,
    pitchVariance: 1,
    cooldownMs: 150,
    maxInstances: 1,
    note: 'raising the rifle; a lowered variant is the same take pitched down',
  },
  {
    name: 'casing',
    kind: 'sfx',
    prompt: 'single spent brass rifle casing bouncing and rolling on wet concrete, small bright metallic tinks with a tiny splash, close, dry',
    seconds: 0.9,
    variants: 4,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.35,
    volumeVariance: 0.2,
    pitchVariance: 2,
    cooldownMs: 80,
    maxInstances: 4,
    note: 'a beat after each player shot, at the feet',
  },

  // ---- impacts ---------------------------------------------------------------------
  {
    name: 'impact-concrete',
    kind: 'sfx',
    prompt: 'bullet impact on concrete wall, sharp crack with stone chips and dust, close, dry, no ricochet whine',
    seconds: 0.7,
    variants: 4,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.55,
    volumeVariance: 0.15,
    pitchVariance: 2,
    cooldownMs: 30,
    maxInstances: 6,
  },
  {
    name: 'impact-metal',
    kind: 'sfx',
    prompt: 'bullet impact on a hollow steel panel, ringing metallic clang with a short ricochet spang, close, dry',
    seconds: 0.9,
    variants: 4,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.55,
    volumeVariance: 0.15,
    pitchVariance: 2,
    cooldownMs: 30,
    maxInstances: 6,
  },
  {
    name: 'impact-glass',
    kind: 'sfx',
    prompt: 'bullet hitting a thick window, sharp glass crack and a scatter of small shards, close, dry',
    seconds: 0.9,
    variants: 3,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.55,
    volumeVariance: 0.15,
    pitchVariance: 1.5,
    cooldownMs: 30,
    maxInstances: 4,
  },
  {
    name: 'impact-water',
    kind: 'sfx',
    prompt: 'bullet hitting a shallow puddle on asphalt, quick sharp splash with a wet slap, close, dry',
    seconds: 0.7,
    variants: 3,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.5,
    volumeVariance: 0.15,
    pitchVariance: 2,
    cooldownMs: 30,
    maxInstances: 4,
  },
  {
    name: 'impact-flesh',
    kind: 'sfx',
    prompt: 'bullet hitting a body, wet heavy thud with a fabric puncture, visceral, close, dry, no scream',
    seconds: 0.6,
    variants: 4,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.7,
    volumeVariance: 0.12,
    pitchVariance: 1.5,
    cooldownMs: 30,
    maxInstances: 4,
  },
  {
    name: 'impact-head',
    kind: 'sfx',
    prompt: 'bullet hitting a helmet and skull, hard wet crack with a metallic snap, gory, close, dry',
    seconds: 0.6,
    variants: 3,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.8,
    volumeVariance: 0.1,
    pitchVariance: 1,
    cooldownMs: 30,
    maxInstances: 3,
  },
  {
    name: 'whiz',
    kind: 'sfx',
    prompt: 'bullet passing very close to the listener, fast supersonic whip crack and zip, stereo pass-by, dry',
    seconds: 0.6,
    variants: 3,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.5,
    volumeVariance: 0.15,
    pitchVariance: 2,
    cooldownMs: 90,
    maxInstances: 3,
    stereo: true,
    note: 'an enemy round that misses the operator by under two metres',
  },

  // ---- bodies and gore ----------------------------------------------------------------
  {
    name: 'blood-splatter',
    kind: 'sfx',
    prompt: 'wet blood splatter hitting a concrete wall and dripping, thick liquid splash, close, dry',
    seconds: 0.9,
    variants: 3,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.45,
    volumeVariance: 0.15,
    pitchVariance: 1.5,
    cooldownMs: 60,
    maxInstances: 3,
  },
  {
    name: 'body-fall',
    kind: 'sfx',
    prompt: 'a body in tactical gear collapsing onto wet asphalt, heavy dull thud with a splash and gear rattle, close, dry',
    seconds: 1.2,
    variants: 3,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.7,
    volumeVariance: 0.1,
    pitchVariance: 1,
    cooldownMs: 200,
    maxInstances: 3,
  },

  // ---- movement --------------------------------------------------------------------
  {
    name: 'footstep-walk',
    kind: 'sfx',
    prompt: 'single footstep of a combat boot on wet concrete, soft heel then sole, small water squelch, close mic, dry',
    seconds: 0.5,
    variants: 6,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.45,
    volumeVariance: 0.2,
    pitchVariance: 1.5,
    cooldownMs: 90,
    maxInstances: 6,
  },
  {
    name: 'footstep-run',
    kind: 'sfx',
    prompt: 'single hard running footstep of a combat boot slapping wet asphalt, splash and grit, close mic, dry',
    seconds: 0.5,
    variants: 6,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.6,
    volumeVariance: 0.2,
    pitchVariance: 1.5,
    cooldownMs: 90,
    maxInstances: 6,
  },
  {
    name: 'gear-rustle',
    kind: 'sfx',
    prompt: 'tactical vest and nylon straps rustling with a soft buckle tick, one short movement, close, dry',
    seconds: 0.6,
    variants: 4,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.3,
    volumeVariance: 0.2,
    pitchVariance: 1.5,
    cooldownMs: 150,
    maxInstances: 3,
    note: 'stance changes, landing',
  },
  {
    name: 'land',
    kind: 'sfx',
    prompt: 'two combat boots landing from a jump onto wet concrete together, heavy thud with a splash and gear rattle, close, dry',
    seconds: 0.8,
    variants: 3,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.65,
    volumeVariance: 0.1,
    pitchVariance: 1,
    cooldownMs: 300,
    maxInstances: 2,
  },

  // ---- player ----------------------------------------------------------------------------
  {
    name: 'hurt',
    kind: 'sfx',
    prompt: 'a man grunting sharply in pain through clenched teeth after being shot, short breathy grunt, close, dry, no words',
    seconds: 0.8,
    variants: 4,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.6,
    volumeVariance: 0.1,
    pitchVariance: 1,
    cooldownMs: 250,
    maxInstances: 1,
  },
  {
    name: 'death-player',
    kind: 'sfx',
    prompt: 'a man exhaling a last choked breath and collapsing, heartbeat slowing and stopping, muffled, cinematic, no words',
    seconds: 3.0,
    variants: 1,
    influence: 0.45,
    bus: 'sfx',
    volume: 0.8,
    maxInstances: 1,
    stereo: true,
  },
  {
    name: 'heartbeat',
    kind: 'sfx',
    prompt: 'slow heavy human heartbeat, deep muffled thumps, steady rhythm around sixty beats per minute, seamless loop',
    seconds: 4.0,
    loop: true,
    influence: 0.5,
    bus: 'sfx',
    volume: 0.0,
    stereo: true,
    note: 'low-health loop; gain follows health below 35 percent',
  },

  // ---- enemy voice (text-to-speech, helmet comms filter in the build) ------------------------
  { name: 'bark-suspicious', kind: 'voice', prompt: 'Huh? ... Who\'s there?', seconds: 0, variants: 1, bus: 'sfx', volume: 0.85, cooldownMs: 1500, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-suspicious-2', kind: 'voice', prompt: 'Did you hear that?', seconds: 0, variants: 1, bus: 'sfx', volume: 0.85, cooldownMs: 1500, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-alert', kind: 'voice', prompt: 'Contact! Contact!', seconds: 0, variants: 1, bus: 'sfx', volume: 0.95, cooldownMs: 800, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-alert-2', kind: 'voice', prompt: 'There! Light him up!', seconds: 0, variants: 1, bus: 'sfx', volume: 0.95, cooldownMs: 800, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-alert-3', kind: 'voice', prompt: 'We got a runner! Take him down!', seconds: 0, variants: 1, bus: 'sfx', volume: 0.95, cooldownMs: 800, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-search', kind: 'voice', prompt: 'Lost him. Spread out.', seconds: 0, variants: 1, bus: 'sfx', volume: 0.85, cooldownMs: 1500, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-search-2', kind: 'voice', prompt: 'Where did he go? Check the alley.', seconds: 0, variants: 1, bus: 'sfx', volume: 0.85, cooldownMs: 1500, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-reload', kind: 'voice', prompt: 'Reloading! Cover me!', seconds: 0, variants: 1, bus: 'sfx', volume: 0.85, cooldownMs: 1500, maxInstances: 2, voiceStyle: 'ganger' },
  { name: 'bark-hit', kind: 'voice', prompt: 'Argh!', seconds: 0, variants: 2, bus: 'sfx', volume: 0.8, cooldownMs: 300, maxInstances: 3, voiceStyle: 'ganger' },
  { name: 'bark-death', kind: 'voice', prompt: 'Aaagh... no...', seconds: 0, variants: 2, bus: 'sfx', volume: 0.85, cooldownMs: 300, maxInstances: 3, voiceStyle: 'ganger' },

  // ---- ambience ---------------------------------------------------------------------------
  {
    name: 'rain-bed',
    kind: 'sfx',
    prompt: 'steady heavy night rain on a city street, rain hitting asphalt and puddles, distant hiss on rooftops, wide stereo, seamless loop, no thunder',
    seconds: 22,
    loop: true,
    influence: 0.5,
    bus: 'ambience',
    volume: 0.7,
    stereo: true,
    lufs: -24,
  },
  {
    name: 'city-bed',
    kind: 'sfx',
    prompt: 'distant futuristic city at night, low traffic rumble, far off sirens and a passing hover vehicle drone, air conditioning units humming, very distant, wide stereo, seamless loop, no rain',
    seconds: 22,
    loop: true,
    influence: 0.45,
    bus: 'ambience',
    volume: 0.45,
    stereo: true,
    lufs: -28,
  },
  {
    name: 'neon-buzz',
    kind: 'sfx',
    prompt: 'neon sign transformer hum and buzz with an occasional electrical flicker crackle, close mic, mono, seamless loop',
    seconds: 6,
    loop: true,
    variants: 2,
    influence: 0.55,
    bus: 'ambience',
    volume: 0.55,
    pitchVariance: 1,
    lufs: -27,
    note: 'one voice per neon light, attached to the light position',
  },
  {
    name: 'steam-hiss',
    kind: 'sfx',
    prompt: 'steam venting from a street grate, steady pressurised hiss with soft gurgles, close mic, mono, seamless loop',
    seconds: 6,
    loop: true,
    variants: 2,
    influence: 0.55,
    bus: 'ambience',
    volume: 0.6,
    pitchVariance: 1,
    lufs: -26,
    note: 'one voice per authored steam vent',
  },
  {
    name: 'drip',
    kind: 'sfx',
    prompt: 'single water drop falling from a fire escape into a puddle, small clean plink with a tiny splash, close, dry',
    seconds: 0.6,
    variants: 5,
    influence: 0.55,
    bus: 'ambience',
    volume: 0.4,
    volumeVariance: 0.3,
    pitchVariance: 3,
    cooldownMs: 200,
    maxInstances: 4,
    note: 'scattered around the listener on a random timer',
  },
  {
    name: 'thunder',
    kind: 'sfx',
    prompt: 'distant rolling thunder over a city, long low rumble without a sharp crack, far away, wide stereo, no rain',
    seconds: 6,
    variants: 3,
    influence: 0.5,
    bus: 'ambience',
    volume: 0.6,
    volumeVariance: 0.2,
    pitchVariance: 1,
    cooldownMs: 15000,
    maxInstances: 1,
    stereo: true,
    lufs: -22,
  },
  {
    name: 'drone-pass',
    kind: 'sfx',
    prompt: 'a small surveillance drone flying past overhead in the rain, rotor whine with doppler pitch drop, stereo pass-by',
    seconds: 5,
    variants: 2,
    influence: 0.5,
    bus: 'ambience',
    volume: 0.5,
    pitchVariance: 1.5,
    cooldownMs: 20000,
    maxInstances: 1,
    stereo: true,
    lufs: -24,
  },

  // ---- interface and objectives ---------------------------------------------------------------------
  {
    name: 'ui-hitmarker',
    kind: 'sfx',
    prompt: 'tiny sharp digital tick confirming a hit, very short clean high click, UI sound',
    seconds: 0.5,
    variants: 1,
    influence: 0.6,
    bus: 'ui',
    volume: 0.5,
    cooldownMs: 40,
    maxInstances: 3,
  },
  {
    name: 'ui-headshot',
    kind: 'sfx',
    prompt: 'short bright two-tone digital confirmation chime, glassy, UI sound',
    seconds: 0.6,
    variants: 1,
    influence: 0.6,
    bus: 'ui',
    volume: 0.5,
    cooldownMs: 100,
    maxInstances: 2,
  },
  {
    name: 'ui-objective',
    kind: 'sfx',
    prompt: 'tactical HUD objective complete notification, a short rising three-note synth confirmation with a soft digital sweep',
    seconds: 1.5,
    variants: 1,
    influence: 0.55,
    bus: 'ui',
    volume: 0.7,
    maxInstances: 1,
    stereo: true,
  },
  {
    name: 'ui-checkpoint',
    kind: 'sfx',
    prompt: 'subtle low digital pulse confirming a save, a single soft warm tone with a brief shimmer',
    seconds: 1.0,
    variants: 1,
    influence: 0.55,
    bus: 'ui',
    volume: 0.5,
    maxInstances: 1,
  },
  {
    name: 'ui-plant-loop',
    kind: 'sfx',
    prompt: 'demolition charge being armed: rhythmic electronic beeps accelerating slightly with a keypad tapping and a device hum, seamless loop',
    seconds: 3.0,
    loop: true,
    influence: 0.55,
    bus: 'sfx',
    volume: 0.6,
    note: 'while F is held at the plant point; pitch rises with progress',
  },
  {
    name: 'ui-plant-done',
    kind: 'sfx',
    prompt: 'demolition charge armed confirmation, a firm electronic lock click followed by a long descending beep',
    seconds: 1.5,
    variants: 1,
    influence: 0.6,
    bus: 'sfx',
    volume: 0.8,
    maxInstances: 1,
  },
  {
    name: 'ui-complete',
    kind: 'sfx',
    prompt: 'mission complete stinger, dark cinematic synth swell resolving into a warm brass-like chord with rain in the background, five seconds, no drums',
    seconds: 5,
    variants: 1,
    influence: 0.45,
    bus: 'ui',
    volume: 0.8,
    maxInstances: 1,
    stereo: true,
    lufs: -16,
  },
  {
    name: 'ui-failed',
    kind: 'sfx',
    prompt: 'mission failed stinger, a low dissonant synth drone dropping in pitch with a distant heartbeat, cold, four seconds, no drums',
    seconds: 4,
    variants: 1,
    influence: 0.45,
    bus: 'ui',
    volume: 0.8,
    maxInstances: 1,
    stereo: true,
    lufs: -18,
  },
  {
    name: 'ui-alert',
    kind: 'sfx',
    prompt: 'short tense low synth hit, a single dark pulse announcing detection, subtle',
    seconds: 1.2,
    variants: 1,
    influence: 0.5,
    bus: 'ui',
    volume: 0.6,
    cooldownMs: 4000,
    maxInstances: 1,
    stereo: true,
    note: 'the moment the first hostile goes alert',
  },
  {
    name: 'ui-lockdown',
    kind: 'sfx',
    prompt: 'heavy descending industrial klaxon swell, two low blares over a rising dread pad, cyberpunk sector lockdown, no melody',
    seconds: 2.6,
    variants: 1,
    influence: 0.55,
    bus: 'ui',
    volume: 0.7,
    cooldownMs: 8000,
    maxInstances: 1,
    stereo: true,
    note: 'the sector escalates to lockdown and sends the second wave (mission/Alert.ts); until it is generated the alert sting stands in',
  },
];

export function cueByName(name) {
  return CUES.find((c) => c.name === name) ?? null;
}
